version: '2'

services:
  web:
    image: 'thinkingserious/web'
    restart: always
    build: ./services/web
    ports:
      - "8000"
    environment:
      - GITHUB_MANAGER_MICROSERVICES_IP=nginx
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  email:
    image: 'thinkingserious/email'
    restart: always
    build: ./services/email
    ports:
      - "8000"
    environment:
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  github:
    image: 'thinkingserious/github'
    restart: always
    build: ./services/github
    ports:
      - "8000"
    environment:
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - APP_SETTINGS=project.config.BaseConfig
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app

  nginx:
    image: 'thinkingserious/nginx'
    restart: always
    build: ./services/nginx
    ports:
      - "80:80"
    links:
      - web:web
    environment:
        - GET_HOSTS_FROM=dns

  sms:
    image: 'thinkingserious/sms'
    restart: always
    build: ./services/sms
    ports:
      - "8000"
    environment:
      - TWILIO_ACCOUNT_SID=${TWILIO_ACCOUNT_SID}
      - TWILIO_AUTH_TOKEN=${TWILIO_AUTH_TOKEN}
    command: /usr/local/bin/gunicorn -w 2 -b :8000 app:app
